# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(354, 560)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 240, 121, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.go_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.go_button.setObjectName("go_button")
        self.verticalLayout.addWidget(self.go_button)
        self.record_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.record_button.setObjectName("record_button")
        self.verticalLayout.addWidget(self.record_button)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 331, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.account_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.account_button.setObjectName("account_button")
        self.horizontalLayout.addWidget(self.account_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Settings_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Settings_button.setObjectName("Settings_button")
        self.horizontalLayout.addWidget(self.Settings_button)
        self.tip_label = QtWidgets.QLabel(self.centralwidget)
        self.tip_label.setGeometry(QtCore.QRect(110, 450, 141, 49))
        self.tip_label.setObjectName("tip_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 354, 22))
        self.menubar.setObjectName("menubar")
        self.menuMaiGO = QtWidgets.QMenu(self.menubar)
        self.menuMaiGO.setObjectName("menuMaiGO")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMaiGO.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.go_button.setText(_translate("MainWindow", "出发！"))
        self.record_button.setText(_translate("MainWindow", "记录"))
        self.account_button.setText(_translate("MainWindow", "账号"))
        self.Settings_button.setText(_translate("MainWindow", "设置"))
        self.tip_label.setText(_translate("MainWindow", "可以跟我打一辈子舞萌吗"))
        self.menuMaiGO.setTitle(_translate("MainWindow", "MaiGO!!!!!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
