# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartWidget(object):
    def setupUi(self, StartWidget):
        StartWidget.setObjectName("StartWidget")
        StartWidget.resize(325, 591)
        self.verticalLayoutWidget = QtWidgets.QWidget(StartWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 300, 141, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.go_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.go_button.setObjectName("go_button")
        self.verticalLayout.addWidget(self.go_button)
        self.record_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.record_button.setObjectName("record_button")
        self.verticalLayout.addWidget(self.record_button)
        self.horizontalLayoutWidget = QtWidgets.QWidget(StartWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 281, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.account_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.account_button.setObjectName("account_button")
        self.horizontalLayout.addWidget(self.account_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.settings_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.settings_button.setObjectName("settings_button")
        self.horizontalLayout.addWidget(self.settings_button)
        self.label = QtWidgets.QLabel(StartWidget)
        self.label.setGeometry(QtCore.QRect(100, 520, 311, 20))
        self.label.setObjectName("label")

        self.retranslateUi(StartWidget)
        QtCore.QMetaObject.connectSlotsByName(StartWidget)

    def retranslateUi(self, StartWidget):
        _translate = QtCore.QCoreApplication.translate
        StartWidget.setWindowTitle(_translate("StartWidget", "开始界面"))
        self.go_button.setText(_translate("StartWidget", "出发"))
        self.record_button.setText(_translate("StartWidget", "记录"))
        self.account_button.setText(_translate("StartWidget", "账号"))
        self.settings_button.setText(_translate("StartWidget", "设置"))
        self.label.setText(_translate("StartWidget", "可以和我打一辈子舞萌吗"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StartWidget = QtWidgets.QWidget()
    ui = Ui_StartWidget()
    ui.setupUi(StartWidget)
    StartWidget.show()
    sys.exit(app.exec_())
