# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\cjdl\vsc\homework\ChSh\MaiGO\ui_class\data_single.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataSingle(object):
    def setupUi(self, DataSingle):
        DataSingle.setObjectName("DataSingle")
        DataSingle.resize(553, 173)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DataSingle.sizePolicy().hasHeightForWidth())
        DataSingle.setSizePolicy(sizePolicy)
        DataSingle.setMaximumSize(QtCore.QSize(16777215, 400))
        self.horizontalLayout = QtWidgets.QHBoxLayout(DataSingle)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.single_layout = QtWidgets.QVBoxLayout()
        self.single_layout.setObjectName("single_layout")
        self.data_label = QtWidgets.QLabel(DataSingle)
        self.data_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.data_label.setObjectName("data_label")
        self.single_layout.addWidget(self.data_label)
        self.horizontalLayout.addLayout(self.single_layout)

        self.retranslateUi(DataSingle)
        QtCore.QMetaObject.connectSlotsByName(DataSingle)

    def retranslateUi(self, DataSingle):
        _translate = QtCore.QCoreApplication.translate
        DataSingle.setWindowTitle(_translate("DataSingle", "Form"))
        self.data_label.setText(_translate("DataSingle", "数据"))
