# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\cjdl\vsc\homework\ChSh\MaiGO\ui_class\go_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GoWidget(object):
    def setupUi(self, GoWidget):
        GoWidget.setObjectName("GoWidget")
        GoWidget.resize(336, 472)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/bear.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        GoWidget.setWindowIcon(icon)
        GoWidget.setStyleSheet("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(GoWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.goal_label = QtWidgets.QLabel(GoWidget)
        self.goal_label.setAutoFillBackground(False)
        self.goal_label.setStyleSheet("font: 15pt \"黑体\";")
        self.goal_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.goal_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.goal_label.setMidLineWidth(0)
        self.goal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.goal_label.setObjectName("goal_label")
        self.verticalLayout_2.addWidget(self.goal_label)
        self.time_label = QtWidgets.QLabel(GoWidget)
        self.time_label.setStyleSheet("QLabel#time_label{\n"
"    font: 14pt \"Noto Serif SC Black\";\n"
"}\n"
"")
        self.time_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.verticalLayout_2.addWidget(self.time_label, 0, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(GoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.state_label = QtWidgets.QLabel(GoWidget)
        self.state_label.setStyleSheet("font: 10pt \"黑体\";\n"
"color: rgb(35, 116, 0);")
        self.state_label.setAlignment(QtCore.Qt.AlignCenter)
        self.state_label.setObjectName("state_label")
        self.verticalLayout_2.addWidget(self.state_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.main_button = QtWidgets.QPushButton(GoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_button.sizePolicy().hasHeightForWidth())
        self.main_button.setSizePolicy(sizePolicy)
        self.main_button.setMinimumSize(QtCore.QSize(150, 60))
        self.main_button.setMaximumSize(QtCore.QSize(150, 60))
        self.main_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.main_button.setStyleSheet("font: 14pt \"黑体\";\n"
"border-radius: 30px;      /* 圆角半径（像素） */\n"
"    background-color: #4CAF50; /* 背景颜色 */\n"
"    color: white;             /* 文字颜色 */\n"
"    border: 5px solid #45a049; /* 边框样式 */")
        self.main_button.setObjectName("main_button")
        self.horizontalLayout_2.addWidget(self.main_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.option_button = QtWidgets.QPushButton(GoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.option_button.sizePolicy().hasHeightForWidth())
        self.option_button.setSizePolicy(sizePolicy)
        self.option_button.setMinimumSize(QtCore.QSize(150, 60))
        self.option_button.setMaximumSize(QtCore.QSize(150, 60))
        self.option_button.setStyleSheet("font: 14pt \"黑体\";\n"
"border-radius: 30px;      /* 圆角半径（像素） */\n"
"    background-color:rgb(80, 194, 255);\n"
"    color: white;             /* 文字颜色 */\n"
"    border: 5px solid rgb(53, 144, 255); /* 边框样式 */")
        self.option_button.setObjectName("option_button")
        self.horizontalLayout_3.addWidget(self.option_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tips_label = QtWidgets.QLabel(GoWidget)
        self.tips_label.setStyleSheet("font: 10pt \"黑体\";\n"
"color: rgb(0, 90, 158);")
        self.tips_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tips_label.setObjectName("tips_label")
        self.verticalLayout_2.addWidget(self.tips_label)

        self.retranslateUi(GoWidget)
        QtCore.QMetaObject.connectSlotsByName(GoWidget)

    def retranslateUi(self, GoWidget):
        _translate = QtCore.QCoreApplication.translate
        GoWidget.setWindowTitle(_translate("GoWidget", "开始界面"))
        self.goal_label.setText(_translate("GoWidget", "目的地："))
        self.time_label.setText(_translate("GoWidget", "0:00"))
        self.state_label.setText(_translate("GoWidget", "state"))
        self.main_button.setText(_translate("GoWidget", "出发"))
        self.option_button.setText(_translate("GoWidget", "选项"))
        self.tips_label.setText(_translate("GoWidget", "TextLabel"))
import resources_rc
