# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\cjdl\vsc\homework\ChSh\MaiGO\ui_class\go_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GoWidget(object):
    def setupUi(self, GoWidget):
        GoWidget.setObjectName("GoWidget")
        GoWidget.resize(246, 369)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/bear.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        GoWidget.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(GoWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.goal_label = QtWidgets.QLabel(GoWidget)
        self.goal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.goal_label.setObjectName("goal_label")
        self.verticalLayout_2.addWidget(self.goal_label)
        self.time_label = QtWidgets.QLabel(GoWidget)
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.verticalLayout_2.addWidget(self.time_label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(GoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.state_label = QtWidgets.QLabel(GoWidget)
        self.state_label.setAlignment(QtCore.Qt.AlignCenter)
        self.state_label.setObjectName("state_label")
        self.verticalLayout_2.addWidget(self.state_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.main_button = QtWidgets.QPushButton(GoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_button.sizePolicy().hasHeightForWidth())
        self.main_button.setSizePolicy(sizePolicy)
        self.main_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.main_button.setObjectName("main_button")
        self.horizontalLayout_2.addWidget(self.main_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.option_button = QtWidgets.QPushButton(GoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.option_button.sizePolicy().hasHeightForWidth())
        self.option_button.setSizePolicy(sizePolicy)
        self.option_button.setObjectName("option_button")
        self.horizontalLayout_3.addWidget(self.option_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(GoWidget)
        QtCore.QMetaObject.connectSlotsByName(GoWidget)

    def retranslateUi(self, GoWidget):
        _translate = QtCore.QCoreApplication.translate
        GoWidget.setWindowTitle(_translate("GoWidget", "开始界面"))
        self.goal_label.setText(_translate("GoWidget", "目的地："))
        self.time_label.setText(_translate("GoWidget", "0:00"))
        self.label_2.setText(_translate("GoWidget", "旅行伙伴们"))
        self.state_label.setText(_translate("GoWidget", "state"))
        self.main_button.setText(_translate("GoWidget", "出发"))
        self.option_button.setText(_translate("GoWidget", "选项"))
import resources_rc
