# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\程序设计实习\MaiGO\ui_class\map_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MapWidget(object):
    def setupUi(self, MapWidget):
        MapWidget.setObjectName("MapWidget")
        MapWidget.resize(415, 417)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/bear.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MapWidget.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(MapWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(MapWidget)
        self.label.setStyleSheet("QLabel#label{\n"
"    font: 14pt \"Book Antiqua\";\n"
"    background-color:rgb(242, 234, 255)\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.view = QtWidgets.QGraphicsView(MapWidget)
        self.view.setObjectName("view")
        self.verticalLayout_2.addWidget(self.view)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.return_button = QtWidgets.QPushButton(MapWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.return_button.sizePolicy().hasHeightForWidth())
        self.return_button.setSizePolicy(sizePolicy)
        self.return_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(185, 219, 255);  /* 蓝色背景 */\n"
"    color: rgb(0, 0, 0);\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 8px 16px;\n"
"    font: 14pt \"STHupo\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(103, 202, 255);  /* 悬停变深蓝 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(101, 206, 255);  /* 按下颜色 */\n"
"}")
        self.return_button.setObjectName("return_button")
        self.horizontalLayout.addWidget(self.return_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(MapWidget)
        QtCore.QMetaObject.connectSlotsByName(MapWidget)

    def retranslateUi(self, MapWidget):
        _translate = QtCore.QCoreApplication.translate
        MapWidget.setWindowTitle(_translate("MapWidget", "开始界面"))
        self.label.setText(_translate("MapWidget", "机厅地图"))
        self.return_button.setText(_translate("MapWidget", "返回"))
import resources_rc
