# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\程序设计实习\MaiGO\ui_class\map_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MapWidget(object):
    def setupUi(self, MapWidget):
        MapWidget.setObjectName("MapWidget")
        MapWidget.resize(415, 417)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/bear.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MapWidget.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(MapWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(MapWidget)
        self.label.setStyleSheet("font: 14pt \"黑体\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.view = QtWidgets.QGraphicsView(MapWidget)
        self.view.setObjectName("view")
        self.verticalLayout_2.addWidget(self.view)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.return_button = QtWidgets.QPushButton(MapWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.return_button.sizePolicy().hasHeightForWidth())
        self.return_button.setSizePolicy(sizePolicy)
        self.return_button.setMinimumSize(QtCore.QSize(150, 60))
        self.return_button.setMaximumSize(QtCore.QSize(150, 60))
        self.return_button.setStyleSheet("font: 14pt \"黑体\";\n"
"border-radius: 30px;      /* 圆角半径（像素） */\n"
"    background-color:rgb(80, 194, 255);\n"
"    color: white;             /* 文字颜色 */\n"
"    border: 5px solid rgb(53, 144, 255); /* 边框样式 */")
        self.return_button.setObjectName("return_button")
        self.horizontalLayout.addWidget(self.return_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(MapWidget)
        QtCore.QMetaObject.connectSlotsByName(MapWidget)

    def retranslateUi(self, MapWidget):
        _translate = QtCore.QCoreApplication.translate
        MapWidget.setWindowTitle(_translate("MapWidget", "开始界面"))
        self.label.setText(_translate("MapWidget", "机厅地图"))
        self.return_button.setText(_translate("MapWidget", "返回"))
import resources_rc
