# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\程序设计实习\MaiGO\ui_class\option_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OptionWidget(object):
    def setupUi(self, OptionWidget):
        OptionWidget.setObjectName("OptionWidget")
        OptionWidget.resize(347, 520)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OptionWidget.sizePolicy().hasHeightForWidth())
        OptionWidget.setSizePolicy(sizePolicy)
        OptionWidget.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(OptionWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(OptionWidget)
        self.label.setStyleSheet("font: 14pt \"黑体\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.inform_layout = QtWidgets.QVBoxLayout()
        self.inform_layout.setObjectName("inform_layout")
        self.options_scroll = QtWidgets.QScrollArea(OptionWidget)
        self.options_scroll.setWidgetResizable(True)
        self.options_scroll.setAlignment(QtCore.Qt.AlignCenter)
        self.options_scroll.setObjectName("options_scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 325, 339))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.options_scroll.setWidget(self.scrollAreaWidgetContents)
        self.inform_layout.addWidget(self.options_scroll)
        self.verticalLayout.addLayout(self.inform_layout)
        self.return_button = QtWidgets.QPushButton(OptionWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.return_button.sizePolicy().hasHeightForWidth())
        self.return_button.setSizePolicy(sizePolicy)
        self.return_button.setMinimumSize(QtCore.QSize(150, 60))
        self.return_button.setMaximumSize(QtCore.QSize(150, 60))
        self.return_button.setStyleSheet("font: 14pt \"黑体\";\n"
"border-radius: 30px;      /* 圆角半径（像素） */\n"
"    background-color:rgb(80, 194, 255);\n"
"    color: white;             /* 文字颜色 */\n"
"    border: 5px solid rgb(53, 144, 255); /* 边框样式 */")
        self.return_button.setObjectName("return_button")
        self.verticalLayout.addWidget(self.return_button, 0, QtCore.Qt.AlignHCenter)
        self.Fixed_button = QtWidgets.QPushButton(OptionWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Fixed_button.sizePolicy().hasHeightForWidth())
        self.Fixed_button.setSizePolicy(sizePolicy)
        self.Fixed_button.setMinimumSize(QtCore.QSize(150, 60))
        self.Fixed_button.setMaximumSize(QtCore.QSize(150, 60))
        self.Fixed_button.setStyleSheet("font: 14pt \"黑体\";\n"
"border-radius: 30px;      /* 圆角半径（像素） */\n"
"    background-color: #4CAF50; /* 背景颜色 */\n"
"    color: white;             /* 文字颜色 */\n"
"    border: 5px solid #45a049; /* 边框样式 */")
        self.Fixed_button.setObjectName("Fixed_button")
        self.verticalLayout.addWidget(self.Fixed_button, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(OptionWidget)
        QtCore.QMetaObject.connectSlotsByName(OptionWidget)

    def retranslateUi(self, OptionWidget):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("OptionWidget", "选项"))
        self.return_button.setText(_translate("OptionWidget", "取消"))
        self.Fixed_button.setText(_translate("OptionWidget", "确定"))
