# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\程序设计实习\MaiGO\ui_class\option_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OptionSelect(object):
    def setupUi(self, OptionSelect):
        OptionSelect.setObjectName("OptionSelect")
        OptionSelect.resize(357, 196)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OptionSelect.sizePolicy().hasHeightForWidth())
        OptionSelect.setSizePolicy(sizePolicy)
        OptionSelect.setMaximumSize(QtCore.QSize(16777215, 400))
        self.horizontalLayout = QtWidgets.QHBoxLayout(OptionSelect)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.option_box = QtWidgets.QGroupBox(OptionSelect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.option_box.sizePolicy().hasHeightForWidth())
        self.option_box.setSizePolicy(sizePolicy)
        self.option_box.setObjectName("option_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.option_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.selection_layout = QtWidgets.QVBoxLayout()
        self.selection_layout.setObjectName("selection_layout")
        self.verticalLayout_2.addLayout(self.selection_layout)
        self.horizontalLayout_2.addWidget(self.option_box)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(OptionSelect)
        QtCore.QMetaObject.connectSlotsByName(OptionSelect)

    def retranslateUi(self, OptionSelect):
        _translate = QtCore.QCoreApplication.translate
        OptionSelect.setWindowTitle(_translate("OptionSelect", "Form"))
        self.option_box.setTitle(_translate("OptionSelect", "操作名"))
