# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\程序设计实习\MaiGO\ui_class\record_single.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecordSingle(object):
    def setupUi(self, RecordSingle):
        RecordSingle.setObjectName("RecordSingle")
        RecordSingle.resize(391, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RecordSingle.sizePolicy().hasHeightForWidth())
        RecordSingle.setSizePolicy(sizePolicy)
        RecordSingle.setMaximumSize(QtCore.QSize(16777215, 100))
        self.horizontalLayout = QtWidgets.QHBoxLayout(RecordSingle)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.time_label = QtWidgets.QLabel(RecordSingle)
        self.time_label.setObjectName("time_label")
        self.verticalLayout.addWidget(self.time_label)
        self.goal_label = QtWidgets.QLabel(RecordSingle)
        self.goal_label.setObjectName("goal_label")
        self.verticalLayout.addWidget(self.goal_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.info_button = QtWidgets.QPushButton(RecordSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_button.sizePolicy().hasHeightForWidth())
        self.info_button.setSizePolicy(sizePolicy)
        self.info_button.setMinimumSize(QtCore.QSize(150, 60))
        self.info_button.setMaximumSize(QtCore.QSize(150, 60))
        self.info_button.setStyleSheet("font: 14pt \"黑体\";\n"
"border-radius: 30px;      /* 圆角半径（像素） */\n"
"    background-color:rgb(80, 194, 255);\n"
"    color: white;             /* 文字颜色 */\n"
"    border: 5px solid rgb(53, 144, 255); /* 边框样式 */")
        self.info_button.setObjectName("info_button")
        self.horizontalLayout_2.addWidget(self.info_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(RecordSingle)
        QtCore.QMetaObject.connectSlotsByName(RecordSingle)

    def retranslateUi(self, RecordSingle):
        _translate = QtCore.QCoreApplication.translate
        RecordSingle.setWindowTitle(_translate("RecordSingle", "Form"))
        self.time_label.setText(_translate("RecordSingle", "时间"))
        self.goal_label.setText(_translate("RecordSingle", "目的地"))
        self.info_button.setText(_translate("RecordSingle", "详情"))
