# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\cjdl\vsc\homework\ChSh\MaiGO\ui_class\record_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecordInfo(object):
    def setupUi(self, RecordInfo):
        RecordInfo.setObjectName("RecordInfo")
        RecordInfo.resize(400, 300)
        self.record_label = QtWidgets.QLabel(RecordInfo)
        self.record_label.setGeometry(QtCore.QRect(130, 110, 54, 12))
        self.record_label.setObjectName("record_label")

        self.retranslateUi(RecordInfo)
        QtCore.QMetaObject.connectSlotsByName(RecordInfo)

    def retranslateUi(self, RecordInfo):
        _translate = QtCore.QCoreApplication.translate
        RecordInfo.setWindowTitle(_translate("RecordInfo", "Form"))
        self.record_label.setText(_translate("RecordInfo", "TextLabel"))
