# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\cjdl\vsc\homework\ChSh\MaiGO\ui_class\record_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecordWidget(object):
    def setupUi(self, RecordWidget):
        RecordWidget.setObjectName("RecordWidget")
        RecordWidget.resize(347, 520)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RecordWidget.sizePolicy().hasHeightForWidth())
        RecordWidget.setSizePolicy(sizePolicy)
        RecordWidget.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(RecordWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(RecordWidget)
        self.label.setStyleSheet("font: 14pt \"黑体\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.inform_layout = QtWidgets.QVBoxLayout()
        self.inform_layout.setObjectName("inform_layout")
        self.record_scroll = QtWidgets.QScrollArea(RecordWidget)
        self.record_scroll.setWidgetResizable(True)
        self.record_scroll.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.record_scroll.setObjectName("record_scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 325, 423))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.record_scroll.setWidget(self.scrollAreaWidgetContents)
        self.inform_layout.addWidget(self.record_scroll)
        self.verticalLayout.addLayout(self.inform_layout)
        self.bottom_layout = QtWidgets.QHBoxLayout()
        self.bottom_layout.setObjectName("bottom_layout")
        self.return_button = QtWidgets.QPushButton(RecordWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.return_button.sizePolicy().hasHeightForWidth())
        self.return_button.setSizePolicy(sizePolicy)
        self.return_button.setMinimumSize(QtCore.QSize(80, 40))
        self.return_button.setMaximumSize(QtCore.QSize(80, 40))
        self.return_button.setStyleSheet("font: 14pt \"黑体\";\n"
"border-radius: 20px;      /* 圆角半径（像素） */\n"
"    background-color:rgb(80, 194, 255);\n"
"    color: white;             /* 文字颜色 */\n"
"    border: 5px solid rgb(53, 144, 255); /* 边框样式 */")
        self.return_button.setObjectName("return_button")
        self.bottom_layout.addWidget(self.return_button)
        self.verticalLayout.addLayout(self.bottom_layout)

        self.retranslateUi(RecordWidget)
        QtCore.QMetaObject.connectSlotsByName(RecordWidget)

    def retranslateUi(self, RecordWidget):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("RecordWidget", "记录"))
        self.return_button.setText(_translate("RecordWidget", "返回"))
