# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\cjdl\vsc\homework\ChSh\MaiGO\ui_class\record_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecordInfo(object):
    def setupUi(self, RecordInfo):
        RecordInfo.setObjectName("RecordInfo")
        RecordInfo.resize(347, 520)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RecordInfo.sizePolicy().hasHeightForWidth())
        RecordInfo.setSizePolicy(sizePolicy)
        RecordInfo.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(RecordInfo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(RecordInfo)
        self.label.setStyleSheet("QLabel#label{\n"
"    font: 14pt \"Book Antiqua\";\n"
"    background-color:rgb(242, 234, 255)\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.inform_layout = QtWidgets.QVBoxLayout()
        self.inform_layout.setObjectName("inform_layout")
        self.info_scroll = QtWidgets.QScrollArea(RecordInfo)
        self.info_scroll.setWidgetResizable(True)
        self.info_scroll.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_scroll.setObjectName("info_scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 325, 422))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.info_scroll.setWidget(self.scrollAreaWidgetContents)
        self.inform_layout.addWidget(self.info_scroll)
        self.verticalLayout.addLayout(self.inform_layout)
        self.bottom_layout = QtWidgets.QHBoxLayout()
        self.bottom_layout.setObjectName("bottom_layout")
        self.return_button = QtWidgets.QPushButton(RecordInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.return_button.sizePolicy().hasHeightForWidth())
        self.return_button.setSizePolicy(sizePolicy)
        self.return_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(185, 219, 255);  /* 蓝色背景 */\n"
"    color: rgb(0, 0, 0);\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 8px 16px;\n"
"    font: 14pt \"STHupo\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(103, 202, 255);  /* 悬停变深蓝 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(101, 206, 255);  /* 按下颜色 */\n"
"}")
        self.return_button.setObjectName("return_button")
        self.bottom_layout.addWidget(self.return_button)
        self.verticalLayout.addLayout(self.bottom_layout)

        self.retranslateUi(RecordInfo)
        QtCore.QMetaObject.connectSlotsByName(RecordInfo)

    def retranslateUi(self, RecordInfo):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("RecordInfo", "详情"))
        self.return_button.setText(_translate("RecordInfo", "返回"))
