# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\程序设计实习\MaiGO\ui_class\record_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecordInfo(object):
    def setupUi(self, RecordInfo):
        RecordInfo.setObjectName("RecordInfo")
        RecordInfo.resize(391, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RecordInfo.sizePolicy().hasHeightForWidth())
        RecordInfo.setSizePolicy(sizePolicy)
        RecordInfo.setMaximumSize(QtCore.QSize(16777215, 300))
        self.horizontalLayout = QtWidgets.QHBoxLayout(RecordInfo)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.info_label = QtWidgets.QLabel(RecordInfo)
        self.info_label.setStyleSheet("font: 14pt \"黑体\";")
        self.info_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.info_label.setObjectName("info_label")
        self.verticalLayout.addWidget(self.info_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.return_button = QtWidgets.QPushButton(RecordInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.return_button.sizePolicy().hasHeightForWidth())
        self.return_button.setSizePolicy(sizePolicy)
        self.return_button.setMinimumSize(QtCore.QSize(80, 40))
        self.return_button.setMaximumSize(QtCore.QSize(80, 40))
        self.return_button.setStyleSheet("font: 14pt \"黑体\";\n"
"border-radius: 20px;      /* 圆角半径（像素） */\n"
"    background-color:rgb(80, 194, 255);\n"
"    color: white;             /* 文字颜色 */\n"
"    border: 5px solid rgb(53, 144, 255); /* 边框样式 */")
        self.return_button.setObjectName("return_button")
        self.horizontalLayout_2.addWidget(self.return_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(RecordInfo)
        QtCore.QMetaObject.connectSlotsByName(RecordInfo)

    def retranslateUi(self, RecordInfo):
        _translate = QtCore.QCoreApplication.translate
        RecordInfo.setWindowTitle(_translate("RecordInfo", "Form"))
        self.info_label.setText(_translate("RecordInfo", "详情"))
        self.return_button.setText(_translate("RecordInfo", "返回"))
