# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\cjdl\vsc\homework\ChSh\MaiGO\ui_class\record_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecordInterface(object):
    def setupUi(self, RecordInterface):
        RecordInterface.setObjectName("RecordInterface")
        RecordInterface.resize(391, 128)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RecordInterface.sizePolicy().hasHeightForWidth())
        RecordInterface.setSizePolicy(sizePolicy)
        RecordInterface.setMaximumSize(QtCore.QSize(16777215, 150))
        self.horizontalLayout = QtWidgets.QHBoxLayout(RecordInterface)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.time_label = QtWidgets.QLabel(RecordInterface)
        self.time_label.setStyleSheet("font: 12pt \"黑体\";")
        self.time_label.setObjectName("time_label")
        self.verticalLayout.addWidget(self.time_label)
        self.goal_label = QtWidgets.QLabel(RecordInterface)
        self.goal_label.setStyleSheet("font: 12pt \"黑体\";")
        self.goal_label.setObjectName("goal_label")
        self.verticalLayout.addWidget(self.goal_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.info_button = QtWidgets.QPushButton(RecordInterface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_button.sizePolicy().hasHeightForWidth())
        self.info_button.setSizePolicy(sizePolicy)
        self.info_button.setMinimumSize(QtCore.QSize(150, 60))
        self.info_button.setMaximumSize(QtCore.QSize(150, 60))
        self.info_button.setStyleSheet("font: 14pt \"黑体\";\n"
"border-radius: 30px;      /* 圆角半径（像素） */\n"
"    background-color:rgb(80, 194, 255);\n"
"    color: white;             /* 文字颜色 */\n"
"    border: 5px solid rgb(53, 144, 255); /* 边框样式 */")
        self.info_button.setObjectName("info_button")
        self.horizontalLayout_2.addWidget(self.info_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(RecordInterface)
        QtCore.QMetaObject.connectSlotsByName(RecordInterface)

    def retranslateUi(self, RecordInterface):
        _translate = QtCore.QCoreApplication.translate
        RecordInterface.setWindowTitle(_translate("RecordInterface", "Form"))
        self.time_label.setText(_translate("RecordInterface", "时间"))
        self.goal_label.setText(_translate("RecordInterface", "目的地"))
        self.info_button.setText(_translate("RecordInterface", "详情"))
