# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\cjdl\vsc\homework\ChSh\MaiGO\ui_class\settings_single.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsSingle(object):
    def setupUi(self, SettingsSingle):
        SettingsSingle.setObjectName("SettingsSingle")
        SettingsSingle.resize(553, 173)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsSingle.sizePolicy().hasHeightForWidth())
        SettingsSingle.setSizePolicy(sizePolicy)
        SettingsSingle.setMaximumSize(QtCore.QSize(16777215, 400))
        self.horizontalLayout = QtWidgets.QHBoxLayout(SettingsSingle)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.single_layout = QtWidgets.QVBoxLayout()
        self.single_layout.setObjectName("single_layout")
        self.horizontalLayout.addLayout(self.single_layout)

        self.retranslateUi(SettingsSingle)
        QtCore.QMetaObject.connectSlotsByName(SettingsSingle)

    def retranslateUi(self, SettingsSingle):
        _translate = QtCore.QCoreApplication.translate
        SettingsSingle.setWindowTitle(_translate("SettingsSingle", "Form"))
