# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\程序设计实习\MaiGO\ui_class\select_single.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectSingle(object):
    def setupUi(self, SelectSingle):
        SelectSingle.setObjectName("SelectSingle")
        SelectSingle.resize(269, 48)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SelectSingle.sizePolicy().hasHeightForWidth())
        SelectSingle.setSizePolicy(sizePolicy)
        SelectSingle.setMaximumSize(QtCore.QSize(16777215, 400))
        self.horizontalLayout = QtWidgets.QHBoxLayout(SelectSingle)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_label = QtWidgets.QLabel(SelectSingle)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout.addWidget(self.name_label)
        self.radioButton = QtWidgets.QRadioButton(SelectSingle)
        self.radioButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton.setText("")
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)

        self.retranslateUi(SelectSingle)
        QtCore.QMetaObject.connectSlotsByName(SelectSingle)

    def retranslateUi(self, SelectSingle):
        _translate = QtCore.QCoreApplication.translate
        SelectSingle.setWindowTitle(_translate("SelectSingle", "Form"))
        self.name_label.setText(_translate("SelectSingle", "TextLabel"))
