# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\程序设计实习\MaiGO\ui_class\start_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartWidget(object):
    def setupUi(self, StartWidget):
        StartWidget.setObjectName("StartWidget")
        StartWidget.resize(274, 383)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/bear.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        StartWidget.setWindowIcon(icon)
        StartWidget.setStyleSheet("QWidget#StartWidget {\n"
"        border-image: url(:/image/friend.png) 0 0 0 0 round round;\n"
"    }\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(StartWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.account_button = QtWidgets.QPushButton(StartWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_button.sizePolicy().hasHeightForWidth())
        self.account_button.setSizePolicy(sizePolicy)
        self.account_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(185, 219, 255);  /* 蓝色背景 */\n"
"    color: rgb(0, 0, 0);\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 8px 16px;\n"
"    font: 14pt \"华文彩云\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(103, 202, 255);  /* 悬停变深蓝 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(101, 206, 255);  /* 按下颜色 */\n"
"}")
        self.account_button.setObjectName("account_button")
        self.horizontalLayout.addWidget(self.account_button)
        spacerItem = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.settings_button = QtWidgets.QPushButton(StartWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_button.sizePolicy().hasHeightForWidth())
        self.settings_button.setSizePolicy(sizePolicy)
        self.settings_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(185, 219, 255);  /* 蓝色背景 */\n"
"    color: rgb(0, 0, 0);\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 8px 16px;\n"
"    font: 14pt \"华文彩云\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(103, 202, 255);  /* 悬停变深蓝 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(101, 206, 255);  /* 按下颜色 */\n"
"}")
        self.settings_button.setObjectName("settings_button")
        self.horizontalLayout.addWidget(self.settings_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.go_button = QtWidgets.QPushButton(StartWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.go_button.sizePolicy().hasHeightForWidth())
        self.go_button.setSizePolicy(sizePolicy)
        self.go_button.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.go_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.go_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(185, 219, 255);  /* 蓝色背景 */\n"
"    color: rgb(0, 0, 0);\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 8px 16px;\n"
"    font: 14pt \"STHupo\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(103, 202, 255);  /* 悬停变深蓝 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(101, 206, 255);  /* 按下颜色 */\n"
"}")
        self.go_button.setObjectName("go_button")
        self.verticalLayout.addWidget(self.go_button, 0, QtCore.Qt.AlignHCenter)
        self.record_button = QtWidgets.QPushButton(StartWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.record_button.sizePolicy().hasHeightForWidth())
        self.record_button.setSizePolicy(sizePolicy)
        self.record_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(185, 219, 255);  /* 蓝色背景 */\n"
"    color: rgb(0, 0, 0);\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 8px 16px;\n"
"    font: 14pt \"STHupo\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(103, 202, 255);  /* 悬停变深蓝 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(101, 206, 255);  /* 按下颜色 */\n"
"}")
        self.record_button.setObjectName("record_button")
        self.verticalLayout.addWidget(self.record_button, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.label = QtWidgets.QLabel(StartWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("STHupo")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(170, 0, 127);\n"
"font: 12pt \"STHupo\";\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)

        self.retranslateUi(StartWidget)
        QtCore.QMetaObject.connectSlotsByName(StartWidget)

    def retranslateUi(self, StartWidget):
        _translate = QtCore.QCoreApplication.translate
        StartWidget.setWindowTitle(_translate("StartWidget", "开始界面"))
        self.account_button.setText(_translate("StartWidget", "账号"))
        self.settings_button.setText(_translate("StartWidget", "设置"))
        self.go_button.setText(_translate("StartWidget", "出发"))
        self.record_button.setText(_translate("StartWidget", "记录"))
        self.label.setText(_translate("StartWidget", "可以和我打一辈子舞萌吗♪( ´▽｀)"))
import resources_rc
