# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\程序设计实习\MaiGO\ui_class\settings_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsWidget(object):
    def setupUi(self, SettingsWidget):
        SettingsWidget.setObjectName("SettingsWidget")
        SettingsWidget.resize(347, 520)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsWidget.sizePolicy().hasHeightForWidth())
        SettingsWidget.setSizePolicy(sizePolicy)
        SettingsWidget.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(SettingsWidget)
        self.label.setStyleSheet("font: 14pt \"黑体\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.inform_layout = QtWidgets.QVBoxLayout()
        self.inform_layout.setObjectName("inform_layout")
        self.settings_scroll = QtWidgets.QScrollArea(SettingsWidget)
        self.settings_scroll.setWidgetResizable(True)
        self.settings_scroll.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.settings_scroll.setObjectName("settings_scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 325, 403))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.settings_scroll.setWidget(self.scrollAreaWidgetContents)
        self.inform_layout.addWidget(self.settings_scroll)
        self.verticalLayout.addLayout(self.inform_layout)
        self.bottom_layout = QtWidgets.QHBoxLayout()
        self.bottom_layout.setObjectName("bottom_layout")
        self.return_button = QtWidgets.QPushButton(SettingsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.return_button.sizePolicy().hasHeightForWidth())
        self.return_button.setSizePolicy(sizePolicy)
        self.return_button.setMinimumSize(QtCore.QSize(150, 60))
        self.return_button.setMaximumSize(QtCore.QSize(150, 60))
        self.return_button.setStyleSheet("font: 14pt \"黑体\";\n"
"border-radius: 30px;      /* 圆角半径（像素） */\n"
"    background-color:rgb(80, 194, 255);\n"
"    color: white;             /* 文字颜色 */\n"
"    border: 5px solid rgb(53, 144, 255); /* 边框样式 */")
        self.return_button.setObjectName("return_button")
        self.bottom_layout.addWidget(self.return_button)
        self.verticalLayout.addLayout(self.bottom_layout)

        self.retranslateUi(SettingsWidget)
        QtCore.QMetaObject.connectSlotsByName(SettingsWidget)

    def retranslateUi(self, SettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("SettingsWidget", "设置"))
        self.return_button.setText(_translate("SettingsWidget", "返回"))
