# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\cjdl\vsc\homework\ChSh\MaiGO\ui_class\settings_single.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsSingle(object):
    def setupUi(self, SettingsSingle):
        SettingsSingle.setObjectName("SettingsSingle")
        SettingsSingle.resize(553, 116)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsSingle.sizePolicy().hasHeightForWidth())
        SettingsSingle.setSizePolicy(sizePolicy)
        SettingsSingle.setMaximumSize(QtCore.QSize(16777215, 400))
        self.horizontalLayout = QtWidgets.QHBoxLayout(SettingsSingle)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.name_label = QtWidgets.QLabel(SettingsSingle)
        self.name_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout_2.addWidget(self.name_label)
        self.enable_checkbox = QtWidgets.QCheckBox(SettingsSingle)
        self.enable_checkbox.setMaximumSize(QtCore.QSize(16777215, 16777214))
        self.enable_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.enable_checkbox.setObjectName("enable_checkbox")
        self.horizontalLayout_2.addWidget(self.enable_checkbox)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(SettingsSingle)
        QtCore.QMetaObject.connectSlotsByName(SettingsSingle)

    def retranslateUi(self, SettingsSingle):
        _translate = QtCore.QCoreApplication.translate
        SettingsSingle.setWindowTitle(_translate("SettingsSingle", "Form"))
        self.name_label.setText(_translate("SettingsSingle", "描述"))
        self.enable_checkbox.setText(_translate("SettingsSingle", "未启用"))
